default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: datario-dev
      dataset: dbt
      location: US
      threads: 2
      keyfile: /credentials-dev/dev.json
    prod:
      type: bigquery
      method: service-account
      project: datario
      dataset: dbt
      location: US
      threads: 2
      keyfile: /credentials-prod/prod.json
    compile:
      type: bigquery
      method: service-account
      project: datario-dev
      dataset: dbt
      location: US
      threads: 2
      keyfile: credentials/dev.json
