default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: escritorio-temp
      dataset: dbt_test
      threads: 2
      keyfile: /credentials/dev.json
    prod:
      type: bigquery
      method: service-account
      project: escritorio-temp
      dataset: dbt_test
      threads: 2
      keyfile: /credentials/prod.json
