default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: datario-dev
      dataset: dbt_test
      threads: 2
      keyfile: /credentials-dev/dev.json
    prod:
      type: bigquery
      method: service-account
      project: escritorio-temp
      dataset: datario
      threads: 2
      keyfile: /credentials-prod/prod.json
