---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbt-rpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbt-rpc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: dbt-rpc
    spec:
      containers:
        - name: dbt-rpc
          image: gcr.io/PROJECT_ID/IMAGE_DBT:TAG
          ports:
            - containerPort: 80
          volumeMounts:
            - name: credentials-dev
              mountPath: /credentials-dev/
              readOnly: true
            - name: credentials-prod
              mountPath: /credentials-prod/
              readOnly: true
      volumes:
        - name: credentials-dev
          secret:
            secretName: credentials-dev
        - name: credentials-prod
          secret:
            secretName: credentials-prod
      restartPolicy: Always
