version: 2
models :
  - name: chamado
    description: "**Descrição**: Chamados feitos ao 1746. São chamados desde março\
      \ de  2011, quando começou o projeto 1746.\n**Frequência de atualização**: Diário\n\
      **Cobertura temporal**: Março de  2011\n**Órgão gestor dos dados**: SEGOVI\n\
      **Publicado por**: Patricia Catandi\n**Publicado por (email)**: patriciabcatandi@gmail.com\n"
    columns:
      - name: id_chamado
        description: Identificador único do chamado no banco de dados.
      - name: data_inicio
        description: Data de abertura do chamado. Ocorre quando o operador registra
          o chamado.
      - name: data_fim
        description: Data de fechamento do chamado. O chamado é fechado quando o pedido
          é atendido ou quando se percebe que o pedido não pode ser atendido.
      - name: id_bairro
        description: Identificador único, no banco de dados, do bairro onde ocorreu
          o fato que gerou o chamado.
      - name: id_territorialidade
        description: 'Identificador único, no banco de dados, da territorialidade
          onde ocorreu o fato que gerou o chamado. Territorialidade é uma região da
          cidade do Rio de Janeiro que tem com responsável um órgão especifico. Exemplo:
          CDURP, que é responsável pela região do porto do Rio de Janeiro.'
      - name: id_logradouro
        description: Identificador único, no banco de dados, do logradouro onde ocorreu
          o fato que gerou o chamado.
      - name: numero_logradouro
        description: Número da porta onde ocorreu o fato que gerou o chamado.
      - name: id_unidade_organizacional
        description: 'Identificador único, no banco de dados, do órgão que executa
          o chamado. Por exemplo: identificador da COMLURB quando o chamado é relativo
          a limpeza urbana.'
      - name: nome_unidade_organizacional
        description: 'Nome do órgão que executa a demanda. Por exemplo: COMLURB quando
          a demanda é relativa a limpeza urbana.'
      - name: unidade_organizadional_ouvidoria
        description: Booleano indicando se o chamado do cidadão foi feita Ouvidoria
          ou não. 1 caso sim, 0 caso não,
      - name: categoria
        description: 'Categoria do chamado. Exemplo: Serviço, informação, sugestão,
          elogio, reclamação, crítica.'
      - name: id_tipo
        description: 'Identificador único, no banco de dados, do tipo do chamado.
          Ex: Iluminação pública.'
      - name: tipo
        description: 'Nome do tipo do chamado. Ex: Iluminação pública.'
      - name: id_subtipo
        description: 'Identificador único, no banco de dados, do subtipo do chamado.
          Ex: Reparo de lâmpada apagada.'
      - name: subtipo
        description: 'Nome do subtipo do chamado.  Ex: Reparo de lâmpada apagada.'
      - name: status
        description: Status do chamado. Ex. Fechado com solução, aberto em andamento,
          pendente etc.
      - name: longitude
        description: Longitude do lugar do evento que motivou o chamado.
      - name: latitude
        description: Latitude do lugar do evento que motivou o chamado.
      - name: data_alvo_finalizacao
        description: Data prevista para o atendimento do chamado. Caso prazo_tipo
          seja D fica em branco até o diagnóstico ser feito.
      - name: data_alvo_diagnostico
        description: Data prevista para fazer o diagnóstico do serviço.  Caso prazo_tipo
          seja F esta data fica em branco.
      - name: data_real_diagnostico
        description: Data em que foi feito o diagnóstico do serviço.  Caso prazo_tipo
          seja F esta data fica em branco.
      - name: prazo
        description: Prazo para o serviço ser feito. Em dias ou horas após a abertura
          do chamado. Caso haja diagnóstico o prazo conta após se fazer o diagnóstico.
      - name: prazo_unidade
        description: Unidade de tempo utilizada no prazo. Dias ou horas. D ou H.
      - name: prazo_tipo
        description: Diagnóstico ou finalização. D ou F. Indica se a chamada precisa
          de diagnóstico ou não. Alguns serviços precisam de avaliação para serem
          feitos, neste caso é feito o diagnóstico. Por exemplo, pode de árvore. Há
          a necessidade de um engenheiro ambiental verificar a necessidade da poda
          ou não.
