name: Metadata Automation

on:
  pull_request:

env:
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}

jobs:
  update-metadata:
    name: Update metadata from Google Sheets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python version
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Python dependencies for actions
        run: |-
          pip install -r requirements-actions.txt

      - name: Update metadata
        run: |-
          python3 .github/workflows/scripts/metadata_automation.py

      - name: Checkout to branch
        run: |-
          git_branch=${GITHUB_HEAD_REF#refs/heads/}
          git checkout $git_branch

      - name: Commit changed files
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          default_author: github_actions
          message: 'Update metadata'
          pathspec_error_handling: exitImmediately
          push: true
